### ISSUE TITLE
Better iOS version detection mechanism

### ISSUE THREAD

**Issue by shunchu** [BlueKai/bluekai-ios-sdk#10]
SDK decides which methods to call in [BlueKai getVendorId] by making os version checks via `[[UIDevice currentDevice] systemVersion]`. Instead, use `[obj respondsToSelector:@selector(method:)]` to determine at runtime if the method is supported. Alternately, use Apple-supplied macros like `__IPHONE_OS_VERSION_MAX_ALLOWED` to cover cases where a customer compiles your SDK with an older iOS SDK than you expected.

Courtesy feedback from PushSpring

**Comment by antonbk** [comment]
getVendorId is no longer supported
