### ISSUE TITLE
Simplify "showSettingsScreen" code

### ISSUE THREAD

**Issue by shunchu** [BlueKai/bluekai-ios-sdk#12]
SDK `showSettingsScreen` seems overly complicated... many lines of code to paint just a few controls on screen. Perhaps factor into its own class, or build it via a `.nib` to make it easy for apps to modify the look and feel as needed. Also, using a `GestureRecognizer` to handle tapping on a check mark might be overly complicated; a `UIButton` with the check mark image would be simpler.

Courtesy feedback from PushSpring

**Comment by antonbk** [comment]
showSettingsScreen is deprecated and is removed in version 3.0 of SDK,
new SDK will not draw any screens, all is in app developer hands
