### ISSUE TITLE
Move from having to load UIWebView to simply calling an endpoint

### ISSUE THREAD

**Issue by shunchu** [BlueKai/bluekai-ios-sdk#13]
Currently the SDK loads a UIWebView which loads the mobile proxy endpoint to use core tag library to process the `phints` and send to the tags servers. It's definitely more efficient to just be able to send the `phints` directly to the tags servers and bypass mobile proxy altogether if it makes sense. Not sure why UIWebView was required on the initial build.

**Comment by antonbk** [comment]
We have two modes of operation now, one of which includes direct tags call. BlueKai coretag that loads inside of mobile proxy web view does a ton of use full operations. Data collected and calculated inside of web view help BlueKai to do better statistical calculations.
