### ISSUE TITLE
Bitcode

### ISSUE THREAD

**Issue by gkcaslan** [BlueKai/bluekai-ios-sdk#23]
Can't archive if bitcode enabled.

ld: bitcode bundle could not be generated because '.../BlueKai/libBlueKai.a(BlueKai.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by antonbk** [comment]
Thanks for reporting the issue.

I have updated last release binary: https://github.com/BlueKai/bluekai-ios-sdk/releases/download/v3.0.1/bluekai-feedback-on-main-queue-bitcode-v3.0.1.zip

**Comment by gkcaslan** [comment]
Archiving problem is solved with new binary.
Thank you!
