### ISSUE TITLE
Consolidate `udpateWith` methods

### ISSUE THREAD

**Issue by shunchu** [BlueKai/bluekai-ios-sdk#9]
BlueKai class has 2 methods for sending user phints up. Implementation of these should use a single code path, instead today they are basically copies of each other's code. Most likely the `update` method taking a single k/v pair should create a temporary dictionary and just pass it into the `update` method written to take a dictionary.

Courtesy feedback from PushSpring

**Comment by antonbk** [comment]
This is fixed in v3. update with key/value, calls internally updateWithDictionary
